/*
DATA ANALYSIS USING SQL QEURIES
*/
-- =================================================================================================

-- 1. What is the total revenue generated by male vs female customers?

SELECT 
	gender,
	SUM(purchase_amount) total_revenue 
FROM CustomerBehavior
GROUP BY gender;

-- 2. Which customers used a discount but still spent more than the average amount?

SELECT 
	customer_id,
	purchase_amount
FROM CustomerBehavior
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM CustomerBehavior);

-- 3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
	item_purchased,
	ROUND(AVG(review_rating), 2) average_review_rating
FROM CustomerBehavior
GROUP BY item_purchased
ORDER BY average_review_rating DESC;

-- 4. Compare the average purchase amounts between standard and express shipping 

SELECT 
	shipping_type,
	AVG(purchase_amount) average_purchase_amount
FROM CustomerBehavior
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- 5. Do subscribed customers spend more?
-- Compare average spent and total revenue between subscribers and non-subscribers.

SELECT
	subscription_status,
	COUNT(customer_id) total_customers,
	AVG(purchase_amount) average_spent,
	SUM(purchase_amount) total_revenue
FROM CustomerBehavior
GROUP BY subscription_status
ORDER BY total_revenue, average_spent DESC;

-- 6. Which 5 products have the highest percentage of purchases with discount applied?

SELECT TOP 5
	item_purchased,
	--COUNT(*) total_purchases,
	ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1
			  ELSE 0 END) * 100 / COUNT(*),2) discount_percentage
FROM CustomerBehavior
GROUP BY item_purchased
ORDER BY  discount_percentage DESC;

-- 7. Segment customers into New, Returning and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

WITH CustomerTotals AS (
    SELECT
        customer_id,
        SUM(previous_purchases) AS total_previous_purchases
    FROM CustomerBehavior
    GROUP BY customer_id
)
SELECT
    CASE
        WHEN total_previous_purchases = 1 THEN 'New'
        WHEN total_previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM CustomerTotals
GROUP BY
    CASE
        WHEN total_previous_purchases = 1 THEN 'New'
        WHEN total_previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END
ORDER BY customer_count DESC;

-- 8. What are the top 3 most purchased products within each category?

SELECT 
    category,
    item_purchased,
    total_purchases
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (PARTITION BY category
                     ORDER BY COUNT(*) DESC) AS rank
    FROM CustomerBehavior
    GROUP BY category, item_purchased
) x
WHERE rank <= 3
ORDER BY category, rank;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) 
-- also likely to subscribe?

SELECT
    subscription_status,
    COUNT(*) AS repeat_buyers
    --SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers
FROM CustomerBehavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contribution of each age group?

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM CustomerBehavior
GROUP BY age_group
ORDER BY total_revenue DESC;
